/**
 * integration-doc.mjs — emit a coding-agent-ready integration bundle into the
 * chunked output dir: INTEGRATION.md (a self-contained "how to wire this engine
 * into an app" guide) + example.mjs (a runnable scenario demo).
 *
 * This is the handoff surface. When a PE analyst says "I'll hand this to my
 * coding agent," the coding agent opens chunked/ and should immediately
 * understand: what the engine is, how to call run(), which inputs are the
 * levers, which outputs are the answers, and how to spot-check correctness —
 * all tailored to THIS model with real names and base-case values.
 *
 * @license MIT
 */
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

function readJSON(p) {
  try { return JSON.parse(readFileSync(p, 'utf-8')); } catch { return null; }
}

function fmtValue(v, format) {
  if (typeof v !== 'number' || !Number.isFinite(v)) return String(v);
  if (format === 'fraction' || format === 'percent') return `${(v * 100).toFixed(1)}%`;
  if (format === 'multiple') return `${v.toFixed(2)}×`;
  if (format === 'currency') {
    const a = Math.abs(v);
    if (a >= 1e9) return `$${(v / 1e9).toFixed(2)}B`;
    if (a >= 1e6) return `$${(v / 1e6).toFixed(1)}M`;
    if (a >= 1e3) return `$${(v / 1e3).toFixed(0)}K`;
    return `$${v.toFixed(0)}`;
  }
  return Number.isInteger(v) ? String(v) : v.toFixed(4);
}

/**
 * Build the integration bundle. Returns { written: string[] }.
 * @param {string} chunkedDir
 * @param {object} [opts] - { modelTitle }
 */
export function emitIntegrationDoc(chunkedDir, opts = {}) {
  const written = [];
  const outputs = readJSON(join(chunkedDir, 'named-outputs.json'));
  const inputs = readJSON(join(chunkedDir, 'named-inputs.json'));
  const manifest = readJSON(join(chunkedDir, 'manifest.json'));
  if (!existsSync(join(chunkedDir, 'engine.js'))) {
    return { written, skipped: 'engine.js not present' };
  }

  const title = opts.modelTitle || outputs?.modelTitle || manifest?.model?.title || 'model';
  const outMap = outputs?.namedOutputs || {};
  const inMap = inputs?.namedInputs || {};
  const outNames = Object.keys(outMap);
  const inNames = Object.keys(inMap);

  // Pick a representative input lever for the worked example: prefer one that
  // affects the most outputs, falling back to the first.
  let leverName = null;
  let bestAffects = -1;
  for (const [n, spec] of Object.entries(inMap)) {
    const a = (spec.affectsOutputs || []).length;
    if (a > bestAffects) { bestAffects = a; leverName = n; }
  }

  const md = renderMarkdown({ title, outMap, inMap, outNames, inNames, leverName, manifest });
  writeFileSync(join(chunkedDir, 'INTEGRATION.md'), md);
  written.push('INTEGRATION.md');

  const ex = renderExample({ outMap, inMap, leverName });
  writeFileSync(join(chunkedDir, 'example.mjs'), ex);
  written.push('example.mjs');

  return { written };
}

function renderMarkdown({ title, outMap, inMap, outNames, inNames, leverName, manifest }) {
  const L = [];
  L.push(`# Integration Guide — ${title}`);
  L.push('');
  L.push('> This folder is a **self-contained JavaScript engine** for a financial model,');
  L.push('> plus a machine-readable contract describing its inputs and outputs. It was');
  L.push('> generated by [excel-to-engine](https://github.com/ebootheee/excel-to-engine).');
  L.push('> You do **not** need Excel, the original `.xlsx`, or any build step to use it.');
  L.push('');
  L.push('**If you are an AI coding agent:** read this file top to bottom, then run');
  L.push('`node example.mjs`. Everything you need to build an app (an LP dashboard, a');
  L.push('what-if explorer, an API) is here. Cell addresses are the stable contract;');
  L.push('the human names below map to them.');
  L.push('');

  // --- TL;DR usage ---
  L.push('## 30-second usage');
  L.push('');
  L.push('```js');
  L.push(`import { run } from './engine.js';`);
  L.push('');
  L.push('// Base case (no overrides):');
  L.push('const base = run();');
  if (outNames.length) {
    const o = outMap[outNames[0]];
    L.push(`console.log(base.values[${JSON.stringify(o.cell)}]);  // ${outNames[0]} = ${fmtValue(o.baseCaseValue, o.format)}`);
  }
  L.push('');
  if (leverName) {
    const lev = inMap[leverName];
    const bumped = typeof lev.default === 'number'
      ? (Math.abs(lev.default) < 2 ? +(lev.default + 0.02).toFixed(4) : Math.round(lev.default * 1.1 * 100) / 100)
      : lev.default;
    L.push('// What-if: change one lever and recompute everything downstream:');
    L.push(`const alt = run({ ${JSON.stringify(lev.cell)}: ${JSON.stringify(bumped)} });  // ${leverName}: ${fmtValue(lev.default, lev.format)} -> ${fmtValue(bumped, lev.format)}`);
    const affected = (lev.affectsOutputs || []).filter(n => outMap[n]);
    if (affected.length) {
      const a = outMap[affected[0]];
      L.push(`console.log(alt.values[${JSON.stringify(a.cell)}]);  // ${affected[0]} responds`);
    }
  }
  L.push('```');
  L.push('');

  // --- The run() API ---
  L.push('## The `run()` API');
  L.push('');
  L.push('```ts');
  L.push('run(');
  L.push('  inputs?: { [cellAddress: string]: number },  // overrides, e.g. { "Assumptions!B4": 14 }');
  L.push('  options?: { strict?: boolean }               // strict: throw if an override cell is unused');
  L.push('): {');
  L.push('  values: { [cellAddress: string]: number },   // every computed cell, keyed by "Sheet!A1"');
  L.push('  kpis:   { [cellAddress: string]: number },   // alias of values');
  L.push('  meta:   { converged, iterations, maxDelta, elapsedMs, ... },');
  L.push('  unknownOverrides: string[]                   // override cells not read by any formula');
  L.push('}');
  L.push('```');
  L.push('');
  L.push('- **Cell-addressed.** Inputs and outputs are keyed by `"Sheet!A1"`. Use the');
  L.push('  tables below to translate human names ⇄ cells.');
  L.push('- **Pure & deterministic.** Same inputs → same outputs. No I/O, no network.');
  L.push('- **A missing cell reads as `0`** inside formulas (safe numeric default).');
  L.push('- `run()` recomputes the *whole* model. For surgical invalidation, use each');
  L.push('  output\'s `dependsOnNamedInputs` / each input\'s `affectsOutputs` (below).');
  L.push('');

  // --- Outputs table ---
  L.push('## Outputs — the answers your app displays');
  L.push('');
  L.push('From `named-outputs.json`. `baseCaseValue` is the value with no overrides —');
  L.push('**spot-check it**: if `run().values[cell]` ≠ `baseCaseValue`, your wiring or the');
  L.push('model changed. Fail your build on mismatch.');
  L.push('');
  const anyClosures = outNames.some(n => Array.isArray(outMap[n].dependsOnNamedInputs));
  if (outNames.length) {
    L.push('| Output | Label | Cell | Base case | Format | Driven by inputs |');
    L.push('|---|---|---|---|---|---|');
    for (const n of outNames) {
      const o = outMap[n];
      const deps = !Array.isArray(o.dependsOnNamedInputs) ? '?'
        : (o.dependsOnNamedInputs.length ? o.dependsOnNamedInputs.join(', ') : '— (static)');
      L.push(`| \`${n}\` | ${o.label || ''} | \`${o.cell}\` | ${fmtValue(o.baseCaseValue, o.format)} | ${o.format || 'number'} | ${deps} |`);
    }
    if (anyClosures) {
      L.push('');
      L.push('> **"Driven by inputs"** lists the named inputs each output transitively');
      L.push('> depends on. **`— (static)`** means no named lever moves it (it\'s a constant');
      L.push('> or driven by cells not exposed as inputs) — don\'t wire it to a slider.');
      L.push('> **`?`** means closures weren\'t computed for this build.');
    }
  } else {
    L.push('_No named outputs were detected. See `manifest.json` and `_labels.json`._');
  }
  L.push('');

  // --- Inputs table ---
  L.push('## Inputs — the levers users can change');
  L.push('');
  if (inNames.length) {
    L.push('From `named-inputs.json`. Pass any of these to `run({ cell: value })`.');
    L.push('`affectsOutputs` tells you which outputs to refresh when a lever moves.');
    L.push('`min`/`max`/`step` are *suggested* slider bounds (centered on the default —');
    L.push('override to taste).');
    L.push('');
    L.push('| Input | Cell | Default | Format | Suggested range | Affects outputs |');
    L.push('|---|---|---|---|---|---|');
    for (const n of inNames) {
      const i = inMap[n];
      const aff = !Array.isArray(i.affectsOutputs) ? '?' : (i.affectsOutputs.join(', ') || '—');
      const range = (i.min != null && i.max != null)
        ? `${fmtValue(i.min, i.format)} – ${fmtValue(i.max, i.format)}${i.step != null ? ` / ${fmtValue(i.step, i.format)}` : ''}`
        : '—';
      L.push(`| \`${n}\` | \`${i.cell}\` | ${fmtValue(i.default, i.format)} | ${i.format || 'number'} | ${range} | ${aff} |`);
    }
    L.push('');
    L.push('> Inputs come from the workbook\'s **defined names** (cells the model author');
    L.push('> explicitly named and that are read by ≥1 formula). They are the model\'s');
    L.push('> intended dials. You can also override *any* cell by address, named or not.');
    L.push('> An override key is the **cell address** (e.g. `run({ "Assumptions!B4": 14 })`),');
    L.push('> not the Excel name. A key that no formula reads is ignored — check');
    L.push('> `run(...).unknownOverrides` to catch typos.');
  } else {
    L.push('_No named inputs were detected (the workbook had no formula-referenced');
    L.push('defined names). You can still override any cell by address — pick the');
    L.push('assumption cells you want to expose from `manifest.json` or `_labels.json`,');
    L.push('and confirm each one is actually read by a formula via `run(..., {strict:true})`._');
  }
  L.push('');

  // --- Files in this folder ---
  L.push('## What\'s in this folder');
  L.push('');
  L.push('| File | What it is |');
  L.push('|---|---|');
  L.push('| `engine.js` | The model. `import { run }` and call it. |');
  L.push('| `sheets/*.mjs` | Per-sheet compute modules (imported by `engine.js`). |');
  L.push('| `named-outputs.json` | name → { cell, baseCaseValue, format, dependsOnNamedInputs }. |');
  L.push('| `named-inputs.json` | name → { cell, default, affectsOutputs }. The levers. |');
  L.push('| `cell-types.json` | cell → "number" \\| "label" \\| "boolean" \\| "empty". |');
  L.push('| `_ground-truth.json` | Every base-case cell value from the original Excel. |');
  L.push('| `_labels.json` | Row/column label text, for building human-readable UIs. |');
  L.push('| `manifest.json` | Semantic map (segments, returns, carry, equity, timeline). |');
  L.push('| `example.mjs` | **Runnable.** `node example.mjs` — base case + a what-if. |');
  L.push('| `INTEGRATION.md` | This file. |');
  L.push('');

  // --- Web app sketch ---
  L.push('## Building an explorable web app (the common ask)');
  L.push('');
  L.push('A minimal LP-facing what-if explorer is three pieces:');
  L.push('');
  L.push('1. **Render the inputs** (`named-inputs.json`) as sliders/number fields,');
  L.push('   seeded with each `default`.');
  L.push('2. **On change**, call `run(overrides)` with the changed cells.');
  L.push('3. **Render the outputs** (`named-outputs.json`) as cards/charts, reading');
  L.push('   `result.values[cell]` and formatting per each output\'s `format`.');
  L.push('');
  L.push('```js');
  L.push(`import { run } from './engine.js';`);
  L.push(`import outputs from './named-outputs.json' with { type: 'json' };`);
  L.push(`import inputs  from './named-inputs.json'  with { type: 'json' };`);
  L.push('');
  L.push('function compute(userOverrides /* { cell: value } */) {');
  L.push('  const { values } = run(userOverrides);');
  L.push('  return Object.fromEntries(');
  L.push('    Object.entries(outputs.namedOutputs).map(([name, o]) => [name, values[o.cell]])');
  L.push('  );');
  L.push('}');
  L.push('```');
  L.push('');
  L.push('The engine runs in Node and in the browser (it\'s plain ES modules with no');
  L.push('dependencies). For a server API, wrap `run()` in an HTTP handler; for a static');
  L.push('site, import it directly.');
  L.push('');

  // --- Accuracy note ---
  L.push('## Accuracy & caveats');
  L.push('');
  L.push('- `engine.run()` executes the model\'s **actual transpiled formulas** — it is');
  L.push('  the exact path, suitable for production app math.');
  L.push('- The `ete` CLI\'s `scenario`/`sensitivity` commands use a faster *first-order');
  L.push('  approximation* (a "delta cascade") for instant analyst queries. For an app');
  L.push('  that needs exact numbers, prefer `run()`.');
  L.push('- Always spot-check `run().values[cell]` against `baseCaseValue` on import. A');
  L.push('  mismatch means the engine was regenerated from a changed model — re-pull the');
  L.push('  contract files.');
  L.push('');
  return L.join('\n') + '\n';
}

function renderExample({ outMap, inMap, leverName }) {
  const outNames = Object.keys(outMap);
  const lev = leverName ? inMap[leverName] : null;
  const bumped = lev && typeof lev.default === 'number'
    ? (Math.abs(lev.default) < 2 ? +(lev.default + 0.02).toFixed(4) : Math.round(lev.default * 1.1 * 100) / 100)
    : null;

  const L = [];
  L.push('// example.mjs — runnable demo for this engine. `node example.mjs`');
  L.push('// Auto-generated by excel-to-engine. Safe to edit/copy.');
  L.push(`import { run } from './engine.js';`);
  L.push('');
  L.push('// name -> cell, inlined from named-outputs.json so this file is standalone:');
  L.push('const OUTPUTS = {');
  for (const n of outNames) {
    L.push(`  ${JSON.stringify(n)}: { cell: ${JSON.stringify(outMap[n].cell)}, base: ${JSON.stringify(outMap[n].baseCaseValue)}, format: ${JSON.stringify(outMap[n].format || 'number')} },`);
  }
  L.push('};');
  L.push('');
  L.push('function fmt(v, f) {');
  L.push('  if (typeof v !== "number" || !isFinite(v)) return String(v);');
  L.push('  if (f === "fraction" || f === "percent") return (v * 100).toFixed(1) + "%";');
  L.push('  if (f === "multiple") return v.toFixed(2) + "x";');
  L.push('  if (f === "currency") return "$" + (Math.abs(v) >= 1e6 ? (v/1e6).toFixed(1) + "M" : v.toLocaleString());');
  L.push('  return String(Math.round(v * 1e4) / 1e4);');
  L.push('}');
  L.push('');
  L.push('// --- 1) Base case ---');
  L.push('const base = run();');
  L.push('console.log("Base case:");');
  L.push('let drift = 0;');
  L.push('for (const [name, o] of Object.entries(OUTPUTS)) {');
  L.push('  const v = base.values[o.cell];');
  L.push('  // Same tolerance as `ete verify` (relative 1e-6 + absolute 1e-6) so the');
  L.push('  // two trust checks never disagree on a rounded base-case value.');
  L.push('  const ok = o.base == null || Math.abs((v ?? 0) - o.base) <= Math.abs(o.base) * 1e-6 + 1e-6;');
  L.push('  if (!ok) drift++;');
  L.push('  console.log(`  ${name.padEnd(20)} ${String(fmt(v, o.format)).padStart(12)}  ${ok ? "" : "  <-- DRIFT vs baseCaseValue " + o.base}`);');
  L.push('}');
  L.push('console.log(drift === 0 ? "  (all outputs match baseCaseValue ✓)" : `  (${drift} output(s) drifted — contract may be stale)`);');
  L.push('');
  if (lev && bumped != null) {
    L.push('// --- 2) What-if: move one lever ---');
    L.push(`const lever = { cell: ${JSON.stringify(lev.cell)}, name: ${JSON.stringify(leverName)}, from: ${JSON.stringify(lev.default)}, to: ${JSON.stringify(bumped)} };`);
    L.push('const alt = run({ [lever.cell]: lever.to });');
    L.push('console.log(`\\nWhat-if: ${lever.name} ${lever.from} -> ${lever.to}`);');
    L.push('for (const [name, o] of Object.entries(OUTPUTS)) {');
    L.push('  const b = base.values[o.cell], a = alt.values[o.cell];');
    L.push('  const moved = typeof a === "number" && typeof b === "number" && Math.abs(a - b) > Math.abs(b) * 1e-9;');
    L.push('  if (moved) console.log(`  ${name.padEnd(20)} ${String(fmt(b,o.format)).padStart(12)} -> ${String(fmt(a,o.format)).padStart(12)}`);');
    L.push('}');
    L.push('if (alt.unknownOverrides?.length) console.log("  note: unused overrides:", alt.unknownOverrides);');
  } else {
    L.push('// --- 2) What-if ---');
    L.push('// No named input levers were detected. Override any cell by address, e.g.:');
    L.push('//   const alt = run({ "Assumptions!B4": 14 });');
    L.push('// Use run(overrides, { strict: true }) to confirm a cell is actually read.');
  }
  L.push('');
  return L.join('\n') + '\n';
}

export default emitIntegrationDoc;
