/// model_map.rs — helpers for building formulas.json and generating raw-engine.js

use crate::dependency::{DependencyGraph, TopoNode};
use crate::formula_ast::parse_formula;
use crate::transpiler::{transpile, TranspileConfig, addr_to_var};
use crate::circular::generate_cluster_loop;
use crate::parser::WorkbookData;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::io::Write;

// ---------------------------------------------------------------------------
// formulas.json schema
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize)]
pub struct FormulaEntry {
    pub qualified_address: String,
    pub sheet: String,
    pub address: String,
    pub formula: String,
    pub js_expr: String,
    pub parse_error: Option<String>,
    pub excel_result: Option<f64>,
}

/// Build formulas.json from all formula cells across all sheets.
pub fn build_formulas_json(workbook: &WorkbookData) -> Vec<FormulaEntry> {
    let mut entries = Vec::new();
    let total_sheets = workbook.sheets.len();

    for (si, sheet) in workbook.sheets.iter().enumerate() {
        eprint!(
            "\r[rust-parser]   Transpiling [{}/{}] {} ({} formulas)...",
            si + 1,
            total_sheets,
            sheet.name,
            sheet.formula_cells.len()
        );
        std::io::stderr().flush().ok();

        let config = TranspileConfig { use_ctx_get: false,
            default_sheet: sheet.name.clone(),
            use_flat_vars: true,
            ..Default::default()
        };

        for cell in &sheet.cells {
            if let Some(formula) = &cell.formula {
                let qualified = format!("{}!{}", sheet.name, cell.address);

                let (js_expr, parse_error) = match parse_formula(formula) {
                    Some(ast) => (transpile(&ast, &config), None),
                    None => (
                        "/* parse error */ 0".to_string(),
                        Some(format!("Could not parse: {}", formula)),
                    ),
                };

                let excel_result = match &cell.value {
                    Some(crate::parser::CellValue::Number(n)) => Some(*n),
                    _ => None,
                };

                entries.push(FormulaEntry {
                    qualified_address: qualified,
                    sheet: sheet.name.clone(),
                    address: cell.address.clone(),
                    formula: formula.clone(),
                    js_expr,
                    parse_error,
                    excel_result,
                });
            }
        }
    }
    eprintln!(); // newline after transpile progress

    entries
}

// ---------------------------------------------------------------------------
// raw-engine.js generation
// ---------------------------------------------------------------------------

pub fn generate_raw_engine(
    workbook: &WorkbookData,
    dep_graph: &DependencyGraph,
    formula_entries: &[FormulaEntry],
    lib_path: &str,
    referenced_cells: &Option<HashSet<String>>,
) -> String {
    let mut lines = Vec::new();

    // Header
    lines.push("// raw-engine.js — AUTO-GENERATED by rust-parser".to_string());
    lines.push("// Do not edit manually — re-run the pipeline to regenerate.".to_string());
    lines.push("// Imports for financial library functions".to_string());
    lines.push(format!("import {{ computeIRR, computeXIRR }} from '{}irr.mjs';", lib_path));
    lines.push(format!("import {{ computeWaterfall }} from '{}waterfall.mjs';", lib_path));
    lines.push("".to_string());

    // Runtime helpers (lookup, etc.)
    lines.push(generate_runtime_helpers());
    lines.push("".to_string());

    // Build lookup maps
    // qualified_address → js_expr
    let formula_map: HashMap<String, String> = formula_entries
        .iter()
        .map(|e| (e.qualified_address.clone(), e.js_expr.clone()))
        .collect();

    // qualified_address → (sheet, address)
    let addr_meta: HashMap<String, (String, String)> = formula_entries
        .iter()
        .map(|e| (e.qualified_address.clone(), (e.sheet.clone(), e.address.clone())))
        .collect();

    // Collect input cells (non-formula numeric cells on first sheet)
    let first_sheet = workbook.sheets.first();
    let _input_cells: Vec<(String, f64)> = first_sheet
        .map(|s| {
            s.cells.iter()
                .filter(|c| c.formula.is_none())
                .filter_map(|c| match &c.value {
                    Some(crate::parser::CellValue::Number(n)) => {
                        Some((c.address.clone(), *n))
                    }
                    _ => None,
                })
                .collect()
        })
        .unwrap_or_default();

    // computeModel function
    lines.push("/**".to_string());
    lines.push(" * Compute the model given inputs.".to_string());
    lines.push(" * @param {Object} inputs - Override any input cell by address".to_string());
    lines.push(" * @returns {Object} outputs - All computed cell values".to_string());
    lines.push(" */".to_string());
    lines.push("export function computeModel(inputs = {}) {".to_string());
    lines.push("  // ── Input cells (override with inputs object) ──────────────────────".to_string());

    // Declare non-formula cells as let vars
    // In compact mode, only declare cells that are actually referenced by formulas
    let mut input_count = 0usize;
    let mut skipped_count = 0usize;
    for sheet in &workbook.sheets {
        let config = TranspileConfig { use_ctx_get: false,
            default_sheet: sheet.name.clone(),
            use_flat_vars: true,
            ..Default::default()
        };
        for cell in &sheet.cells {
            if cell.formula.is_some() {
                continue;
            }
            let qualified = format!("{}!{}", sheet.name, cell.address);
            // In compact mode, skip cells not referenced by any formula
            if let Some(ref refs) = referenced_cells {
                if !refs.contains(&qualified) {
                    skipped_count += 1;
                    continue;
                }
            }
            let var_name = addr_to_var(&sheet.name, &cell.address, &config);
            let default_val = match &cell.value {
                Some(crate::parser::CellValue::Number(n)) => format!("{}", n),
                Some(crate::parser::CellValue::Text(s)) => format!("`{}`",
                    s.replace('\\', "\\\\").replace('`', "\\`").replace("${", "\\${")),
                Some(crate::parser::CellValue::Bool(b)) => b.to_string(),
                _ => "null".to_string(),
            };
            lines.push(format!(
                "  let {} = inputs['{}'] !== undefined ? inputs['{}'] : {};",
                var_name, &qualified, &qualified, default_val
            ));
            input_count += 1;
        }
    }
    if skipped_count > 0 {
        lines.push(format!(
            "  // [compact] {} input cells declared, {} unreferenced cells skipped",
            input_count, skipped_count
        ));
    }

    lines.push("".to_string());
    lines.push("  // ── Formula cells (dependency-ordered) ───────────────────────────────".to_string());

    // Declare all formula cells as let (initially undefined)
    for entry in formula_entries {
        let var_name = addr_to_var(&entry.sheet, &entry.address, &TranspileConfig { use_ctx_get: false,
            default_sheet: entry.sheet.clone(),
            use_flat_vars: true,
            ..Default::default()
        });
        lines.push(format!("  let {} = 0;", var_name));
    }
    lines.push("".to_string());

    // Cells that are inside a convergence cluster
    let cluster_cells: std::collections::HashSet<String> = dep_graph
        .convergence_clusters
        .iter()
        .flat_map(|c| c.cells.iter().cloned())
        .collect();

    // Helper closure: qualified_address → var_name
    let var_for = |addr: &str| -> String {
        if let Some((sheet, cell_addr)) = addr_meta.get(addr) {
            addr_to_var(sheet, cell_addr, &TranspileConfig { use_ctx_get: false,
                default_sheet: sheet.clone(),
                use_flat_vars: true,
                ..Default::default()
            })
        } else {
            // Not a formula cell — it might be an input cell; try to parse sheet!addr
            if let Some(bang) = addr.find('!') {
                let sheet = &addr[..bang];
                let cell_addr = &addr[bang + 1..];
                addr_to_var(sheet, cell_addr, &TranspileConfig { use_ctx_get: false,
                    default_sheet: sheet.to_string(),
                    use_flat_vars: true,
                    ..Default::default()
                })
            } else {
                addr.to_string()
            }
        }
    };

    // Track which cluster IDs have been emitted
    let mut emitted_clusters: std::collections::HashSet<usize> = std::collections::HashSet::new();

    // Walk topo order
    for node in &dep_graph.topo_order {
        match node {
            TopoNode::Single { address } => {
                if cluster_cells.contains(address) {
                    continue; // will be emitted as part of cluster
                }
                if let Some(js_expr) = formula_map.get(address) {
                    let var_name = var_for(address);
                    lines.push(format!("  {} = {};", var_name, js_expr));
                }
            }
            TopoNode::Cluster { id, cells } => {
                if emitted_clusters.contains(id) {
                    continue;
                }
                emitted_clusters.insert(*id);

                // Find the corresponding convergence cluster
                if let Some(cluster) = dep_graph.convergence_clusters.iter().find(|c| c.id == *id) {
                    let code = generate_cluster_loop(cluster, &formula_map, &var_for);
                    lines.push(code.js);
                } else {
                    // Fallback: emit as sequential assignments
                    for addr in cells {
                        if let Some(js_expr) = formula_map.get(addr) {
                            let var_name = var_for(addr);
                            lines.push(format!("  {} = {};", var_name, js_expr));
                        }
                    }
                }
            }
        }
    }

    // Also emit any formula cells not in the topo order (shouldn't happen, but be safe)
    let topo_seen: std::collections::HashSet<String> = dep_graph
        .topo_order
        .iter()
        .flat_map(|n| match n {
            TopoNode::Single { address } => vec![address.clone()],
            TopoNode::Cluster { cells, .. } => cells.clone(),
        })
        .collect();

    for entry in formula_entries {
        if !topo_seen.contains(&entry.qualified_address) {
            let var_name = addr_to_var(&entry.sheet, &entry.address, &TranspileConfig { use_ctx_get: false,
                default_sheet: entry.sheet.clone(),
                use_flat_vars: true,
                ..Default::default()
            });
            lines.push(format!("  {} = {};", var_name, entry.js_expr));
        }
    }

    lines.push("".to_string());
    lines.push("  // ── Collect outputs ──────────────────────────────────────────────────".to_string());
    lines.push("  const outputs = {};".to_string());

    // Collect all computed vars into outputs
    for entry in formula_entries {
        let var_name = addr_to_var(&entry.sheet, &entry.address, &TranspileConfig { use_ctx_get: false,
            default_sheet: entry.sheet.clone(),
            use_flat_vars: true,
            ..Default::default()
        });
        lines.push(format!(
            "  outputs['{}'] = {};",
            entry.qualified_address, var_name
        ));
    }

    lines.push("".to_string());
    lines.push("  return outputs;".to_string());
    lines.push("}".to_string());
    lines.push("".to_string());

    // Export inputs metadata for calibration
    lines.push("// Default inputs (base case from Excel)".to_string());
    lines.push("export const defaultInputs = {".to_string());
    for sheet in &workbook.sheets {
        for cell in &sheet.cells {
            if cell.formula.is_some() {
                continue;
            }
            let qualified = format!("{}!{}", sheet.name, cell.address);
            if let Some(ref refs) = referenced_cells {
                if !refs.contains(&qualified) {
                    continue;
                }
            }
            if let Some(crate::parser::CellValue::Number(n)) = &cell.value {
                lines.push(format!(
                    "  '{}': {},",
                    qualified, n
                ));
            }
        }
    }
    lines.push("};".to_string());

    lines.join("\n")
}

// ---------------------------------------------------------------------------
// Runtime helpers embedded in generated engine
// ---------------------------------------------------------------------------

fn generate_runtime_helpers() -> String {
    r#"// ── Runtime helpers ──────────────────────────────────────────────────────

// VLOOKUP implementation
function _vlookup(val, table, colIdx, exact) {
  if (!Array.isArray(table)) return null;
  const rows = Array.isArray(table[0]) ? table : table.map(v => [v]);
  for (const row of rows) {
    if (exact ? row[0] === val : row[0] <= val) {
      return row[colIdx - 1] ?? null;
    }
  }
  return null;
}

// HLOOKUP implementation
function _hlookup(val, table, rowIdx, exact) {
  if (!Array.isArray(table)) return null;
  const cols = Array.isArray(table[0]) ? table[0] : table;
  const idx = exact
    ? cols.findIndex(v => v === val)
    : cols.reduce((best, v, i) => v <= val ? i : best, -1);
  if (idx < 0) return null;
  if (Array.isArray(table[rowIdx - 1])) return table[rowIdx - 1][idx];
  return null;
}

// MATCH implementation
function _match(val, arr, matchType) {
  if (!Array.isArray(arr)) return null;
  if (matchType === 0) {
    const idx = arr.findIndex(v => v === val);
    return idx >= 0 ? idx + 1 : null;
  }
  if (matchType === 1 || matchType === undefined) {
    let best = -1;
    for (let i = 0; i < arr.length; i++) {
      if (arr[i] <= val) best = i;
      else break;
    }
    return best >= 0 ? best + 1 : null;
  }
  // matchType === -1: descending
  for (let i = 0; i < arr.length; i++) {
    if (arr[i] <= val) return i + 1;
  }
  return null;
}

// INDEX implementation
function _index(arr, rowNum, colNum) {
  if (!Array.isArray(arr)) return arr;
  const row = Array.isArray(arr[0]) ? arr[rowNum - 1] : arr;
  if (Array.isArray(row)) return row[colNum - 1] ?? null;
  return row ?? null;
}

// LARGE/SMALL
function _large(arr, k) {
  if (!Array.isArray(arr)) return null;
  const sorted = [...arr].filter(v => typeof v === 'number').sort((a, b) => b - a);
  return sorted[k - 1] ?? null;
}
function _small(arr, k) {
  if (!Array.isArray(arr)) return null;
  const sorted = [...arr].filter(v => typeof v === 'number').sort((a, b) => a - b);
  return sorted[k - 1] ?? null;
}

// RANK
function _rank(val, arr, order) {
  if (!Array.isArray(arr)) return null;
  const nums = arr.filter(v => typeof v === 'number');
  if (order === 0 || order === undefined) {
    return nums.filter(v => v > val).length + 1;
  }
  return nums.filter(v => v < val).length + 1;
}

// Financial helpers (wrappers — real impl in lib/irr.mjs)
function computeNPV(rate, cashflows) {
  return cashflows.reduce((acc, cf, i) => acc + cf / Math.pow(1 + rate, i + 1), 0);
}
function computePMT(rate, nper, pv) {
  if (rate === 0) return -pv / nper;
  return -pv * rate * Math.pow(1 + rate, nper) / (Math.pow(1 + rate, nper) - 1);
}
function computePV(rate, nper, pmt) {
  if (rate === 0) return -pmt * nper;
  return -pmt * (1 - Math.pow(1 + rate, -nper)) / rate;
}
function computeFV(rate, nper, pmt) {
  if (rate === 0) return -pmt * nper;
  return -pmt * (Math.pow(1 + rate, nper) - 1) / rate;
}
function computeRATE(nper, pmt, pv) {
  // Newton approximation
  let r = 0.1;
  for (let i = 0; i < 100; i++) {
    const f = pv * Math.pow(1+r, nper) + pmt * (Math.pow(1+r, nper) - 1) / r;
    const df = nper * pv * Math.pow(1+r, nper-1) + pmt * (nper * Math.pow(1+r, nper-1) * r - Math.pow(1+r, nper) + 1) / (r * r);
    const dr = -f / df;
    r += dr;
    if (Math.abs(dr) < 1e-10) break;
  }
  return r;
}
function computeNPER(rate, pmt, pv) {
  if (rate === 0) return -pv / pmt;
  return Math.log(-pmt / (pmt + pv * rate)) / Math.log(1 + rate);
}

// Unknown function placeholder
function _fn(name, args) {
  console.warn(`Unsupported Excel function: ${name}`, args);
  return 0;
}"#.to_string()
}
