/// Chunked emitter — generates per-sheet `.mjs` modules, `_graph.json`,
/// `_ground-truth.json`, and `engine.js` orchestrator.
///
/// This implements **Option C: Chunked Compilation** from PLAN-rust-pipeline.md.

use crate::dependency::extract_refs;
use crate::formula_ast::parse_formula;
use crate::parser::{CellValue, WorkbookData};
use crate::sheet_partition::{
    build_sheet_graph, extract_ground_truth, partition_sheets, SheetGraph, SheetPartition,
};
use crate::transpiler::{transpile, TranspileConfig};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::Path;

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Generate all chunked output artifacts into `output_dir`.
/// Returns a summary string of what was emitted.
pub fn emit_chunked(workbook: &WorkbookData, output_dir: &Path) -> Result<String, String> {
    let partitions = partition_sheets(workbook);
    let sheet_graph = build_sheet_graph(&partitions)?;

    // Create sheets/ subdirectory
    let sheets_dir = output_dir.join("sheets");
    fs::create_dir_all(&sheets_dir)
        .map_err(|e| format!("Failed to create sheets/ directory: {}", e))?;

    // 1. Emit per-sheet modules
    let mut sheet_files: Vec<String> = Vec::new();
    for partition in &partitions {
        let code = generate_sheet_module(partition, &workbook);
        let safe_name = sanitize_sheet_name(&partition.name);
        let file_name = format!("{}.mjs", safe_name);
        let file_path = sheets_dir.join(&file_name);
        fs::write(&file_path, &code)
            .map_err(|e| format!("Failed to write {}: {}", file_name, e))?;
        sheet_files.push(file_name);
    }

    // 2. Emit _graph.json
    let graph_json = serde_json::to_string_pretty(&sheet_graph)
        .map_err(|e| format!("Failed to serialize graph: {}", e))?;
    fs::write(output_dir.join("_graph.json"), &graph_json)
        .map_err(|e| format!("Failed to write _graph.json: {}", e))?;

    // 3. Emit _ground-truth.json
    let ground_truth = extract_ground_truth(workbook);
    let gt_json = serde_json::to_string_pretty(&ground_truth)
        .map_err(|e| format!("Failed to serialize ground truth: {}", e))?;
    fs::write(output_dir.join("_ground-truth.json"), &gt_json)
        .map_err(|e| format!("Failed to write _ground-truth.json: {}", e))?;

    // 4. Emit engine.js orchestrator
    let engine_js = generate_orchestrator(&sheet_graph, &partitions);
    fs::write(output_dir.join("engine.js"), &engine_js)
        .map_err(|e| format!("Failed to write engine.js: {}", e))?;

    // Summary
    let summary = format!(
        "Chunked output: {} sheet modules, _graph.json ({} sheets, topo: {:?}), \
         _ground-truth.json ({} entries), engine.js",
        sheet_files.len(),
        sheet_graph.sheets.len(),
        sheet_graph.topo_order,
        ground_truth.len()
    );

    Ok(summary)
}

// ---------------------------------------------------------------------------
// Per-sheet module generation
// ---------------------------------------------------------------------------

/// Generate the JavaScript module code for a single sheet.
fn generate_sheet_module(partition: &SheetPartition, _workbook: &WorkbookData) -> String {
    let mut lines: Vec<String> = Vec::new();
    let sheet_name = &partition.name;

    // Header
    lines.push(format!(
        "// sheets/{}.mjs — AUTO-GENERATED by rust-parser (chunked mode)",
        sanitize_sheet_name(sheet_name)
    ));
    lines.push("// Do not edit manually — re-run the pipeline to regenerate.".to_string());
    lines.push(String::new());

    // Exports: SHEET_NAME, SHEET_DEPENDENCIES
    lines.push(format!(
        "export const SHEET_NAME = \"{}\";",
        escape_js_string(sheet_name)
    ));

    let deps_arr: Vec<String> = partition
        .sheet_dependencies
        .iter()
        .map(|d| format!("\"{}\"", escape_js_string(d)))
        .collect();
    lines.push(format!(
        "export const SHEET_DEPENDENCIES = [{}];",
        deps_arr.join(", ")
    ));
    lines.push(String::new());

    // compute(ctx) function
    lines.push("/**".to_string());
    lines.push(format!(
        " * Compute all cells for sheet \"{}\".",
        escape_js_string(sheet_name)
    ));
    lines.push(" * @param {{Object}} ctx - Context with get(addr), set(addr, val), values map".to_string());
    lines.push(" */".to_string());
    lines.push("export function compute(ctx) {".to_string());

    // Phase 1: input/literal cells
    if !partition.input_cells.is_empty() {
        lines.push("  // ── Literal / input cells ──".to_string());
        for cell in &partition.input_cells {
            let qualified = format!("{}!{}", sheet_name, cell.address);
            let val_js = cell_value_to_js(&cell.value);
            lines.push(format!("  ctx.set(\"{}\", {});", qualified, val_js));
        }
        lines.push(String::new());
    }

    // Phase 2: formula cells — detect intra-sheet cycles and wrap in convergence loops
    if !partition.formula_cells.is_empty() {
        let config = TranspileConfig {
            default_sheet: sheet_name.clone(),
            use_flat_vars: true,
        };

        // Build per-cell transpiled expressions
        let mut cell_exprs: Vec<(String, String)> = Vec::new(); // (qualified_addr, js_expr)
        for cell in &partition.formula_cells {
            if let Some(formula) = &cell.formula {
                let qualified = format!("{}!{}", sheet_name, cell.address);
                let js_expr = match parse_formula(formula) {
                    Some(ast) => {
                        let raw_js = transpile(&ast, &config);
                        convert_vars_to_ctx_get(&raw_js, sheet_name)
                    }
                    None => format!("/* parse error: {} */ 0", escape_js_string(formula)),
                };
                cell_exprs.push((qualified, js_expr));
            }
        }

        // Detect intra-sheet circular references
        let circular_cells = detect_intra_sheet_cycles(partition, sheet_name);

        if circular_cells.is_empty() {
            // No cycles — emit linearly
            lines.push("  // ── Formula cells ──".to_string());
            for (addr, expr) in &cell_exprs {
                lines.push(format!("  ctx.set(\"{}\", {});", addr, expr));
            }
        } else {
            // Split into: pre-cycle, cycle (convergence loop), post-cycle
            let cycle_set: HashSet<String> = circular_cells.iter().cloned().collect();

            // Pre-cycle cells (not in cycle)
            let pre: Vec<&(String, String)> = cell_exprs
                .iter()
                .take_while(|(addr, _)| !cycle_set.contains(addr))
                .collect();

            // Cycle cells
            let cycle: Vec<&(String, String)> = cell_exprs
                .iter()
                .filter(|(addr, _)| cycle_set.contains(addr))
                .collect();

            // Post-cycle cells (after all cycle cells)
            let last_cycle_idx = cell_exprs
                .iter()
                .rposition(|(addr, _)| cycle_set.contains(addr))
                .unwrap_or(0);
            let post: Vec<&(String, String)> = cell_exprs
                .iter()
                .skip(last_cycle_idx + 1)
                .filter(|(addr, _)| !cycle_set.contains(addr))
                .collect();

            if !pre.is_empty() {
                lines.push("  // ── Formula cells (pre-cycle) ──".to_string());
                for (addr, expr) in &pre {
                    lines.push(format!("  ctx.set(\"{}\", {});", addr, expr));
                }
                lines.push(String::new());
            }

            // Convergence loop for circular cells
            lines.push(format!(
                "  // ── Convergence loop ({} circular cells) ──",
                cycle.len()
            ));
            lines.push("  const _maxIter = 100;".to_string());
            lines.push("  const _tol = 1e-8;".to_string());
            lines.push("  for (let _ci = 0; _ci < _maxIter; _ci++) {".to_string());

            // Save previous values of cycle cells
            let cycle_addrs: Vec<String> = cycle.iter().map(|(a, _)| a.clone()).collect();
            lines.push(format!(
                "    const _prev = [{}];",
                cycle_addrs
                    .iter()
                    .map(|a| format!("ctx.get(\"{}\")", a))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));

            // Re-evaluate all cycle cells
            for (addr, expr) in &cycle {
                lines.push(format!("    ctx.set(\"{}\", {});", addr, expr));
            }

            // Also re-evaluate non-cycle cells between the cycle cells that depend on cycle outputs
            let non_cycle_in_range: Vec<&(String, String)> = cell_exprs
                .iter()
                .skip(pre.len())
                .take(last_cycle_idx + 1 - pre.len())
                .filter(|(addr, _)| !cycle_set.contains(addr))
                .collect();
            for (addr, expr) in &non_cycle_in_range {
                lines.push(format!("    ctx.set(\"{}\", {});", addr, expr));
            }

            // Convergence check
            lines.push(format!(
                "    const _curr = [{}];",
                cycle_addrs
                    .iter()
                    .map(|a| format!("ctx.get(\"{}\")", a))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            lines.push(
                "    if (_prev.every((v, i) => Math.abs(v - (_curr[i] || 0)) < _tol)) break;"
                    .to_string(),
            );
            lines.push("  }".to_string());

            if !post.is_empty() {
                lines.push(String::new());
                lines.push("  // ── Formula cells (post-cycle) ──".to_string());
                for (addr, expr) in &post {
                    lines.push(format!("  ctx.set(\"{}\", {});", addr, expr));
                }
            }
        }
    }

    lines.push("}".to_string());
    lines.push(String::new());

    lines.join("\n")
}

/// Convert flat variable references (s_SheetName_A1) to ctx.get("SheetName!A1") calls.
fn convert_vars_to_ctx_get(js: &str, _default_sheet: &str) -> String {
    // Match pattern: s_<SheetName>_<ColRow>
    // We use a simple scan approach since the variable names follow a strict pattern
    let mut result = String::with_capacity(js.len());
    let bytes = js.as_bytes();
    let len = bytes.len();
    let mut i = 0;

    while i < len {
        // Look for s_ prefix that starts a variable reference
        if i + 2 < len && bytes[i] == b's' && bytes[i + 1] == b'_' {
            let start = i;
            i += 2; // skip "s_"

            // Read sheet name part (everything up to the last _ before col+row)
            let mut parts: Vec<u8> = Vec::new();
            while i < len && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                parts.push(bytes[i]);
                i += 1;
            }

            let var_body = String::from_utf8_lossy(&parts).to_string();

            // Parse: find the last underscore that separates sheet name from cell address
            // Cell address is like A1, B12, AA100 (uppercase letters followed by digits)
            if let Some(addr_info) = extract_cell_addr_from_var(&var_body) {
                let sheet_part = &var_body[..var_body.len() - addr_info.len() - 1]; // -1 for underscore
                // Reverse the sanitization: underscores back to spaces (best effort)
                let sheet_name = sheet_part.to_string();
                result.push_str(&format!("ctx.get(\"{}!{}\")", sheet_name, addr_info));
            } else {
                // Couldn't parse — keep original
                result.push_str(&js[start..i]);
            }
        } else {
            result.push(bytes[i] as char);
            i += 1;
        }
    }

    result
}

/// Try to extract a cell address (like "A1", "B12", "AA100") from the end of a variable body.
/// Returns the cell address if found.
fn extract_cell_addr_from_var(var_body: &str) -> Option<String> {
    // Scan from the end: digits first, then uppercase letters
    let bytes = var_body.as_bytes();
    let len = bytes.len();
    if len == 0 {
        return None;
    }

    // Read digits from end
    let mut i = len;
    while i > 0 && bytes[i - 1].is_ascii_digit() {
        i -= 1;
    }
    let digit_start = i;
    if digit_start == len {
        return None; // no digits
    }

    // Read uppercase letters before digits
    while i > 0 && bytes[i - 1].is_ascii_uppercase() {
        i -= 1;
    }
    let letter_start = i;
    if letter_start == digit_start {
        return None; // no letters
    }

    // Must have underscore before the cell address (separator from sheet name)
    if letter_start == 0 {
        return None; // no sheet name
    }
    if bytes[letter_start - 1] != b'_' {
        return None;
    }

    Some(var_body[letter_start..].to_string())
}

// ---------------------------------------------------------------------------
// Orchestrator (engine.js) generation
// ---------------------------------------------------------------------------

fn generate_orchestrator(graph: &SheetGraph, _partitions: &[SheetPartition]) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push("// engine.js — AUTO-GENERATED orchestrator (chunked mode)".to_string());
    lines.push("// Imports sheet modules and executes them in topological order.".to_string());
    lines.push("// Do not edit manually — re-run the pipeline to regenerate.".to_string());
    lines.push(String::new());

    // Import all sheet modules
    for name in &graph.topo_order {
        let safe = sanitize_sheet_name(name);
        lines.push(format!(
            "import {{ compute as compute_{safe}, SHEET_NAME as name_{safe}, SHEET_DEPENDENCIES as deps_{safe} }} from './sheets/{safe}.mjs';",
            safe = safe
        ));
    }
    lines.push(String::new());

    // Runtime context class
    lines.push(generate_ctx_runtime());
    lines.push(String::new());

    // Topo order constant
    let topo_strs: Vec<String> = graph
        .topo_order
        .iter()
        .map(|s| format!("\"{}\"", escape_js_string(s)))
        .collect();
    lines.push(format!(
        "const TOPO_ORDER = [{}];",
        topo_strs.join(", ")
    ));
    lines.push(String::new());

    // Sheet compute map
    lines.push("const SHEET_COMPUTE = {".to_string());
    for name in &graph.topo_order {
        let safe = sanitize_sheet_name(name);
        lines.push(format!(
            "  \"{}\": compute_{},",
            escape_js_string(name),
            safe
        ));
    }
    lines.push("};".to_string());
    lines.push(String::new());

    // run() function
    lines.push("/**".to_string());
    lines.push(" * Execute the full model.".to_string());
    lines.push(" * @param {Object} [inputs] - Optional overrides: { \"Sheet!A1\": value, ... }".to_string());
    lines.push(" * @returns {{ values: Object, kpis: Object }}".to_string());
    lines.push(" */".to_string());
    lines.push("export function run(inputs = {}) {".to_string());
    lines.push("  const ctx = new ComputeContext();".to_string());
    lines.push(String::new());
    lines.push("  // Apply input overrides".to_string());
    lines.push("  for (const [addr, val] of Object.entries(inputs)) {".to_string());
    lines.push("    ctx.set(addr, val);".to_string());
    lines.push("  }".to_string());
    lines.push(String::new());
    lines.push("  // Execute sheets in topological order".to_string());
    lines.push("  for (const sheetName of TOPO_ORDER) {".to_string());
    lines.push("    const computeFn = SHEET_COMPUTE[sheetName];".to_string());
    lines.push("    if (computeFn) {".to_string());
    lines.push("      computeFn(ctx);".to_string());
    lines.push("    }".to_string());
    lines.push("  }".to_string());
    lines.push(String::new());
    lines.push("  return {".to_string());
    lines.push("    values: { ...ctx.values },".to_string());
    lines.push("    kpis: ctx.kpis(),".to_string());
    lines.push("  };".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    // Default export
    lines.push("export default { run };".to_string());
    lines.push(String::new());

    lines.join("\n")
}

fn generate_ctx_runtime() -> String {
    r#"/**
 * ComputeContext — shared state for sheet-level compute functions.
 */
class ComputeContext {
  constructor() {
    /** @type {Object<string, any>} */
    this.values = {};
  }

  /**
   * Get a cell value by qualified address (e.g. "Sheet1!A1").
   * Returns 0 for missing values (safe default for numeric formulas).
   */
  get(addr) {
    const v = this.values[addr];
    return v !== undefined ? v : 0;
  }

  /**
   * Set a cell value by qualified address.
   */
  set(addr, value) {
    this.values[addr] = value;
  }

  /**
   * Get a range of values as a flat array.
   * @param {string} rangeStr - e.g. "Sheet1!A1:B3"
   */
  range(rangeStr) {
    // Simple implementation: match all keys that fall in the range
    const match = rangeStr.match(/^(.+)!([A-Z]+)(\d+):([A-Z]+)(\d+)$/);
    if (!match) return [];
    const [, sheet, col1, row1, col2, row2] = match;
    const c1 = colToNum(col1), c2 = colToNum(col2);
    const r1 = parseInt(row1), r2 = parseInt(row2);
    const result = [];
    for (let r = r1; r <= r2; r++) {
      for (let c = c1; c <= c2; c++) {
        const addr = `${sheet}!${numToCol(c)}${r}`;
        result.push(this.get(addr));
      }
    }
    return result;
  }

  /**
   * Return all formula-computed values as KPI map.
   */
  kpis() {
    return { ...this.values };
  }
}

function colToNum(col) {
  let n = 0;
  for (const ch of col) n = n * 26 + ch.charCodeAt(0) - 64;
  return n;
}
function numToCol(n) {
  let s = '';
  while (n > 0) { n--; s = String.fromCharCode(65 + (n % 26)) + s; n = Math.floor(n / 26); }
  return s;
}"#
    .to_string()
}

// ---------------------------------------------------------------------------
// Intra-sheet cycle detection
// ---------------------------------------------------------------------------

/// Detect cells within a single sheet that form circular references.
/// Returns the set of qualified addresses involved in cycles.
fn detect_intra_sheet_cycles(partition: &SheetPartition, sheet_name: &str) -> Vec<String> {
    // Build intra-sheet dependency graph
    let mut edges: HashMap<String, Vec<String>> = HashMap::new();
    let mut all_addrs: HashSet<String> = HashSet::new();

    for cell in &partition.formula_cells {
        if let Some(formula) = &cell.formula {
            let qualified = format!("{}!{}", sheet_name, cell.address);
            all_addrs.insert(qualified.clone());

            let refs = extract_refs(formula, sheet_name);
            let intra_refs: Vec<String> = refs
                .into_iter()
                .filter(|r| {
                    // Keep only references to cells within this same sheet
                    r.starts_with(&format!("{}!", sheet_name))
                })
                .collect();
            edges.insert(qualified, intra_refs);
        }
    }

    // Simple cycle detection: for each cell, do DFS and check if we can reach ourselves
    let mut in_cycle: HashSet<String> = HashSet::new();

    for start in &all_addrs {
        let mut visited: HashSet<String> = HashSet::new();
        let mut stack: Vec<String> = vec![start.clone()];

        while let Some(node) = stack.pop() {
            if !visited.insert(node.clone()) {
                continue;
            }
            if let Some(deps) = edges.get(&node) {
                for dep in deps {
                    if dep == start && visited.len() > 1 {
                        // Found a cycle back to start
                        in_cycle.insert(start.clone());
                        in_cycle.insert(dep.clone());
                        // Mark all nodes in the path
                        for v in &visited {
                            if all_addrs.contains(v) {
                                if let Some(v_deps) = edges.get(v) {
                                    for vd in v_deps {
                                        if visited.contains(vd) || vd == start {
                                            in_cycle.insert(v.clone());
                                        }
                                    }
                                }
                            }
                        }
                    }
                    if all_addrs.contains(dep) && !visited.contains(dep) {
                        stack.push(dep.clone());
                    }
                }
            }
        }
    }

    // Return in deterministic order
    let mut result: Vec<String> = in_cycle.into_iter().collect();
    result.sort();
    result
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn cell_value_to_js(value: &Option<CellValue>) -> String {
    match value {
        Some(CellValue::Number(n)) => {
            if *n == n.floor() && n.abs() < 1e15 {
                format!("{}", *n as i64)
            } else {
                format!("{}", n)
            }
        }
        Some(CellValue::Text(s)) => format!("`{}`", s.replace('\\', "\\\\").replace('`', "\\`")),
        Some(CellValue::Bool(b)) => b.to_string(),
        Some(CellValue::Error(e)) => format!("/* {} */ null", e),
        Some(CellValue::Empty) | None => "null".to_string(),
    }
}

fn sanitize_sheet_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

fn escape_js_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{CellData, CellValue, SheetData, WorkbookData};

    fn make_cell(
        row: u32,
        col: u32,
        addr: &str,
        val: Option<CellValue>,
        formula: Option<&str>,
    ) -> CellData {
        CellData {
            row,
            col,
            address: addr.to_string(),
            value: val,
            formula: formula.map(|s| s.to_string()),
        }
    }

    fn make_test_workbook() -> WorkbookData {
        let assumptions = SheetData {
            name: "Assumptions".to_string(),
            cells: vec![
                make_cell(0, 0, "A1", Some(CellValue::Text("Revenue".into())), None),
                make_cell(0, 1, "B1", Some(CellValue::Number(1000000.0)), None),
                make_cell(1, 1, "B2", Some(CellValue::Number(0.5)), None),
            ],
            row_count: 2,
            col_count: 2,
            formula_cells: vec![],
        };

        let cashflows = SheetData {
            name: "Cashflows".to_string(),
            cells: vec![
                make_cell(0, 1, "B1", Some(CellValue::Number(1000000.0)), Some("Assumptions!B1")),
                make_cell(1, 1, "B2", Some(CellValue::Number(500000.0)), Some("B1*Assumptions!B2")),
            ],
            row_count: 2,
            col_count: 2,
            formula_cells: vec!["B1".to_string(), "B2".to_string()],
        };

        let summary = SheetData {
            name: "Summary".to_string(),
            cells: vec![
                make_cell(0, 1, "B1", Some(CellValue::Number(1000000.0)), Some("Cashflows!B1")),
            ],
            row_count: 1,
            col_count: 2,
            formula_cells: vec!["B1".to_string()],
        };

        WorkbookData {
            sheet_names: vec!["Assumptions".into(), "Cashflows".into(), "Summary".into()],
            sheets: vec![assumptions, cashflows, summary],
            total_cells: 6,
            total_formula_cells: 3,
        }
    }

    #[test]
    fn test_generate_sheet_module_has_correct_exports() {
        let wb = make_test_workbook();
        let partitions = partition_sheets(&wb);
        let code = generate_sheet_module(&partitions[1], &wb); // Cashflows

        assert!(code.contains("export const SHEET_NAME = \"Cashflows\";"));
        assert!(code.contains("export const SHEET_DEPENDENCIES = [\"Assumptions\"];"));
        assert!(code.contains("export function compute(ctx)"));
        assert!(code.contains("ctx.set(\"Cashflows!B1\""));
        assert!(code.contains("ctx.set(\"Cashflows!B2\""));
    }

    #[test]
    fn test_generate_sheet_module_uses_ctx_get() {
        let wb = make_test_workbook();
        let partitions = partition_sheets(&wb);
        let code = generate_sheet_module(&partitions[1], &wb); // Cashflows

        // Cross-sheet references should use ctx.get()
        assert!(
            code.contains("ctx.get(\"Assumptions!B1\")") || code.contains("ctx.get(\"Assumptions!B2\")"),
            "Should contain ctx.get() for cross-sheet refs. Code:\n{}",
            code
        );
    }

    #[test]
    fn test_extract_cell_addr_from_var() {
        assert_eq!(extract_cell_addr_from_var("Sheet1_A1"), Some("A1".to_string()));
        assert_eq!(extract_cell_addr_from_var("My_Sheet_B12"), Some("B12".to_string()));
        assert_eq!(extract_cell_addr_from_var("X_AA100"), Some("AA100".to_string()));
        assert_eq!(extract_cell_addr_from_var(""), None);
        assert_eq!(extract_cell_addr_from_var("nope"), None);
    }

    #[test]
    fn test_convert_vars_to_ctx_get() {
        let input = "s_Sheet1_A1 + s_Sheet1_B2 * 2";
        let output = convert_vars_to_ctx_get(input, "Sheet1");
        assert!(output.contains("ctx.get(\"Sheet1!A1\")"), "Got: {}", output);
        assert!(output.contains("ctx.get(\"Sheet1!B2\")"), "Got: {}", output);
    }

    #[test]
    fn test_orchestrator_has_imports_and_run() {
        let wb = make_test_workbook();
        let partitions = partition_sheets(&wb);
        let graph = build_sheet_graph(&partitions).unwrap();
        let code = generate_orchestrator(&graph, &partitions);

        assert!(code.contains("import {"), "Should have imports");
        assert!(code.contains("export function run("), "Should have run()");
        assert!(code.contains("TOPO_ORDER"), "Should have topo order");
        assert!(code.contains("class ComputeContext"), "Should have context class");
    }

    #[test]
    fn test_cell_value_to_js() {
        assert_eq!(cell_value_to_js(&Some(CellValue::Number(42.0))), "42");
        assert_eq!(cell_value_to_js(&Some(CellValue::Number(3.14))), "3.14");
        assert_eq!(cell_value_to_js(&Some(CellValue::Bool(true))), "true");
        assert_eq!(cell_value_to_js(&Some(CellValue::Text("hello".into()))), "`hello`");
        assert_eq!(cell_value_to_js(&None), "null");
    }

    #[test]
    fn test_sanitize_sheet_name() {
        assert_eq!(sanitize_sheet_name("Sheet1"), "Sheet1");
        assert_eq!(sanitize_sheet_name("Cash Flow"), "Cash_Flow");
        assert_eq!(sanitize_sheet_name("P&L (2024)"), "P_L__2024_");
    }
}
